name: Run Legislation Info Script and Commit Changes

on:
    workflow_dispatch:  # This enables manual triggering from the GitHub UI
  
jobs:
    update-legislation-info:
      runs-on: ubuntu-latest
  
      steps:
      - name: Check out repository
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version if needed
  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # If you have dependencies
  
      - name: Run legislation info generator script
        run: python scripts/legislation_info_generator.py

      - name: Commit and push if changes
        run: |
          # Set up Git to use the GITHUB_TOKEN for authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          # Git commands to add, commit, and push
          git config --local user.email "bot@example.com"
          git config --local user.name "bot"
          git add public/legislation_info.json"
          git commit -m "Update legislation_info.json"
          git push